// Shared GLOBAL player-identity registry — the single source of truth for player
// identity across all three projects (points-bot, wwc-draft, cricket-auction-helper).
//
// players.json is generated by wwc-points-bot/build_registry.py (the producer / canonical
// source). To refresh, run `npm run sync-registry` — it pulls the latest committed
// registry straight from the wwc-points-bot GitHub repo (no more manual `cp` from a local
// checkout, which silently went stale). The matcher in fuzzy-name-match.ts is now the
// shared `cricket-identity` package; this registry is data, single-sourced via the script.
//
// Each entry is keyed by a stable pid (cricsheet_id when known, else "espn:"/"slug:")
// and lists EVERY feed spelling (aliases, already normalized). This lets the pool
// builders resolve an announced squad name to a DB player by cricsheet_id deterministically
// instead of fuzzy-matching — the same identity the points sheet & draft use.
import registry from "./players.json";

type RegEntry = {
  display: string;
  cricsheet_id: string | null;
  espn_id: string | null;
  aliases: string[];
};

// Mirror of the points-bot `norm()` (hyphen/punct -> space, keep [a-z0-9 ]). NOTE this
// is intentionally DIFFERENT from fuzzy-name-match.ts normName (which drops hyphens with
// no space) — the registry aliases are stored in this form, so both sides must use it.
export function regNorm(s: string): string {
  return (s || "")
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9 ]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const players = (registry as { players: Record<string, RegEntry> }).players;
const aliasToPid = new Map<string, string>();
for (const [pid, e] of Object.entries(players)) {
  for (const a of e.aliases) if (!aliasToPid.has(a)) aliasToPid.set(a, pid);
}

export type ResolvedPlayer = {
  pid: string;
  cricsheetId: string | null;
  espnId: string | null;
  display: string;
};

// Resolve any feed/announced/cricsheet spelling -> the player's global identity.
export function resolveByName(name: string): ResolvedPlayer | null {
  const pid = aliasToPid.get(regNorm(name));
  if (!pid) return null;
  const e = players[pid];
  return { pid, cricsheetId: e.cricsheet_id, espnId: e.espn_id, display: e.display };
}
