// Canonical VENUE identity — the venue counterpart to players.json.
//
// cricsheet stores one ground under 2-4 different `venue_name` strings (it renamed most grounds
// ~2021/22 by appending the city), so 651 strings in our data are really 459 grounds and 67% of all
// matches sit under a split name. Any venue statistic computed on the raw string is therefore built
// on a fragment of that ground's history — and grounds that should be well-sampled get discarded as
// "too thin". Everything that touches a venue must canonicalise FIRST.
//
// venues.json is generated by `python3 data/build_venue_registry.py` (re-run it after an ETL ingest,
// since new grounds appear). Deliberately auction-only — the draft and points bot don't need it.
//
// `espn_venue_id` is reserved and currently null everywhere: ESPN 403s this network on every cricket
// endpoint, so real ids get backfilled later. The slug key is stable in the meantime.
import registry from "./venues.json";

type VenueEntry = {
  canonical: string;
  city: string | null;
  country: string | null;
  espn_venue_id: string | number | null;
  matches: number;
  aliases: string[];
};

const venues = (registry as { venues: Record<string, VenueEntry> }).venues;

// every raw spelling -> its ground's canonical name
const aliasToCanonical = new Map<string, string>();
// canonical -> the registry key (slug), for callers that want a stable id rather than a name
const canonicalToKey = new Map<string, string>();

for (const [key, e] of Object.entries(venues)) {
  canonicalToKey.set(e.canonical, key);
  for (const a of e.aliases) aliasToCanonical.set(a, e.canonical);
}

/**
 * Map any cricsheet venue spelling to its ground's canonical name.
 * Unknown names pass through unchanged — a ground we've never seen is its own ground, which is the
 * safe failure mode (it just won't merge with anything).
 */
export function canonicalVenue(name: string | null | undefined): string {
  if (!name) return "";
  return aliasToCanonical.get(name) ?? name;
}

/** Stable slug id for a ground, or null if it isn't in the registry. */
export function venueKey(name: string | null | undefined): string | null {
  const c = canonicalVenue(name);
  return canonicalToKey.get(c) ?? null;
}

/** Every known cricsheet spelling for the ground that `name` belongs to (including `name`). */
export function venueAliases(name: string | null | undefined): string[] {
  const key = venueKey(name);
  if (!key) return name ? [name] : [];
  return venues[key].aliases;
}

export function venueInfo(name: string | null | undefined): VenueEntry | null {
  const key = venueKey(name);
  return key ? venues[key] : null;
}

export const VENUE_COUNT = Object.keys(venues).length;
